#!/usr/bin/env sh
."$(dirname -- "$0")/_/husky.sh"

echo "Running Prettier and Lint checks"
staged_files=$(git diff --name-only --cached --diff-filter=d)
formatted_files=$(echo "$staged_files" | grep -E '\.(js|css|html)')
files_to_lint=$(echo "$staged_files" | grep -E '\.(js)')

# Prettier로 선택된 파일을 포맷팅하세요. 오류가 있으면 알려주고 실패한 경우 목록을 출력합니다.
echo "$formatted_files" | xargs ./node_modules/.bin/prettier --write --list-different --check || \
(echo "Prettier check failed. See the errors above" && exit 1)

# ESLint로 선택된 파일을 검사하세요. 오류가 있으면 알려주고 실패한 경우 목록을 출력합니다.
echo "$files_to_lint" | xargs ./node_modules/.bin/eslint || (echo "Linting check failed. See the errors above" && exit 1)

# 모든 변경 내용을 다시 추가합니다.
git add $staged_files
